# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5ab8aea6742c6cf1b9af5657246c7afc587ace72900f01694c7a3f81d54cefb134e2931f35ebf96d825bf479abfcc9c7d2ffc25e6b23a1048ec8d938c1203c24

test:
  secret_key_base: 80f514ee6a34fd4e69c0a80d9cba9440ff20c755bddf8fe9b18bca93941328d0834f69c76e4208654a521120445576d3398649f604a9f5781d4ace5cbb131108

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
